language: python
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-gfx-dev

install:
  - pip install --user -U pip
  - pip install --user .

env:
  global:
  - SDL_VIDEODRIVER=dummy
  - SDL_AUDIODRIVER=dummy

script: make runtest
