language: python
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get -qq update
  - sh .travis/install-linux-deps.sh

install:
  - pip install --user -U pip
  - pip install --user .

env:
  global:
  - SDL_VIDEODRIVER=dummy
  - SDL_AUDIODRIVER=dummy
  - SDL_RENDER_DRIVER=software

script: "python -B -m sdl2.test.util.runtests -v"
