language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.4
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
    - os: osx
      language: generic
      env: PYVER=3
    - os: osx
      language: generic
      env: PYVER=2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh .travis/install-linux-deps.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh .travis/install-osx-deps.sh; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh .travis/venv-osx.sh; fi
  - pip install -U pip
  - pip install -U numpy
  - pip install .

env:
  global:
  - SDL_VIDEODRIVER=dummy
  - SDL_AUDIODRIVER=dummy
  - SDL_RENDER_DRIVER=software

script:
  - python -B -m sdl2.test.util.runtests -v
