language: python
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2 libsdl2-image libsdl2-mixer libsdl2-ttf libsdl2-gfx

install:
  - pip install .

script: make runtest
